/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: SemB (https://sketchfab.com/SemBoekenoogen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blimp-enemy-3c10ff21c9b84ea8a067cf8b72ba3f2a
Title: Blimp Enemy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blimp/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Zeppelin_Boss_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/blimp/scene.gltf')
